site_name: DNL1905—Wiki
site_url: http://localhost:8000  # 本地调试无需修改
theme:
  name: material    # 启用material主题

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Dark mode
      primary: light blue
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Light mode
      primary: light blue
      accent: deep orange
  
  logo: images/logo/logo.png

  favicon: images/logo/logo.png